import { Product, Category } from '@/types';

export const categories: Category[] = [
  { id: '1', name: 'Electronics', image: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400' },
  { id: '2', name: 'Fashion', image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400' },
  { id: '3', name: 'Home & Kitchen', image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400' },
  { id: '4', name: 'Books', image: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400' },
  { id: '5', name: 'Sports', image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400' },
  { id: '6', name: 'Toys & Games', image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400' },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Wireless Bluetooth Headphones with Noise Cancellation',
    price: 79.99,
    originalPrice: 129.99,
    rating: 4.5,
    reviews: 2847,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
    category: 'Electronics',
    description: 'Premium wireless headphones with active noise cancellation, 30-hour battery life, and superior sound quality.',
    features: [
      'Active Noise Cancellation',
      '30-hour battery life',
      'Bluetooth 5.0',
      'Comfortable over-ear design',
      'Built-in microphone'
    ],
    inStock: true,
    prime: true,
  },
  {
    id: '2',
    name: 'Smart Watch Fitness Tracker with Heart Rate Monitor',
    price: 149.99,
    originalPrice: 199.99,
    rating: 4.3,
    reviews: 1523,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
    category: 'Electronics',
    description: 'Advanced fitness tracker with heart rate monitoring, GPS, and smartphone notifications.',
    features: [
      'Heart rate monitoring',
      'GPS tracking',
      'Water resistant',
      '7-day battery life',
      'Sleep tracking'
    ],
    inStock: true,
    prime: true,
  },
  {
    id: '3',
    name: 'Ultra HD 4K Smart TV 55-inch',
    price: 499.99,
    originalPrice: 699.99,
    rating: 4.7,
    reviews: 3421,
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500',
    category: 'Electronics',
    description: 'Stunning 4K resolution with HDR support, smart TV features, and voice control.',
    features: [
      '4K Ultra HD resolution',
      'HDR support',
      'Smart TV with streaming apps',
      'Voice control',
      '3 HDMI ports'
    ],
    inStock: true,
    prime: false,
  },
  {
    id: '4',
    name: 'Laptop Backpack with USB Charging Port',
    price: 39.99,
    rating: 4.6,
    reviews: 892,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500',
    category: 'Fashion',
    description: 'Durable laptop backpack with multiple compartments and built-in USB charging port.',
    features: [
      'Fits up to 17-inch laptop',
      'USB charging port',
      'Water-resistant material',
      'Multiple compartments',
      'Comfortable padded straps'
    ],
    inStock: true,
    prime: true,
  },
  {
    id: '5',
    name: 'Stainless Steel Coffee Maker - 12 Cup',
    price: 89.99,
    rating: 4.4,
    reviews: 1247,
    image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=500',
    category: 'Home & Kitchen',
    description: 'Programmable coffee maker with thermal carafe and auto-shutoff feature.',
    features: [
      '12-cup capacity',
      'Programmable timer',
      'Thermal carafe',
      'Auto shutoff',
      'Brew strength control'
    ],
    inStock: true,
    prime: true,
  },
  {
    id: '6',
    name: 'Yoga Mat with Carrying Strap - Extra Thick',
    price: 29.99,
    rating: 4.8,
    reviews: 2156,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500',
    category: 'Sports',
    description: 'Premium yoga mat with extra cushioning and non-slip surface.',
    features: [
      'Extra thick 6mm cushioning',
      'Non-slip surface',
      'Eco-friendly material',
      'Includes carrying strap',
      'Easy to clean'
    ],
    inStock: true,
    prime: true,
  },
  {
    id: '7',
    name: 'Wireless Gaming Mouse with RGB Lighting',
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.5,
    reviews: 1834,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500',
    category: 'Electronics',
    description: 'High-precision gaming mouse with customizable RGB lighting and programmable buttons.',
    features: [
      '16000 DPI sensor',
      'Wireless connectivity',
      'RGB lighting',
      '8 programmable buttons',
      '70-hour battery life'
    ],
    inStock: true,
    prime: true,
  },
  {
    id: '8',
    name: 'Bestselling Mystery Novel - Hardcover',
    price: 24.99,
    rating: 4.7,
    reviews: 5432,
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500',
    category: 'Books',
    description: 'Gripping mystery thriller that will keep you on the edge of your seat.',
    features: [
      'Hardcover edition',
      '400 pages',
      'Bestselling author',
      'Award-winning',
      'Perfect gift'
    ],
    inStock: true,
    prime: true,
  },
  {
    id: '9',
    name: 'Portable Bluetooth Speaker - Waterproof',
    price: 44.99,
    rating: 4.6,
    reviews: 3241,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500',
    category: 'Electronics',
    description: 'Compact waterproof speaker with 360-degree sound and 12-hour battery life.',
    features: [
      'Waterproof IPX7',
      '360-degree sound',
      '12-hour battery',
      'Bluetooth 5.0',
      'Compact and portable'
    ],
    inStock: true,
    prime: true,
  },
  {
    id: '10',
    name: 'Ceramic Non-Stick Cookware Set - 10 Piece',
    price: 129.99,
    originalPrice: 199.99,
    rating: 4.5,
    reviews: 987,
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500',
    category: 'Home & Kitchen',
    description: 'Complete cookware set with ceramic non-stick coating and heat-resistant handles.',
    features: [
      '10-piece set',
      'Ceramic non-stick coating',
      'Dishwasher safe',
      'Oven safe up to 450°F',
      'Heat-resistant handles'
    ],
    inStock: true,
    prime: false,
  },
  {
    id: '11',
    name: 'Running Shoes - Lightweight and Breathable',
    price: 69.99,
    rating: 4.4,
    reviews: 2341,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    category: 'Sports',
    description: 'Comfortable running shoes with responsive cushioning and breathable mesh upper.',
    features: [
      'Lightweight design',
      'Breathable mesh',
      'Responsive cushioning',
      'Durable rubber outsole',
      'Multiple color options'
    ],
    inStock: true,
    prime: true,
  },
  {
    id: '12',
    name: 'Board Game - Strategy and Adventure',
    price: 34.99,
    rating: 4.8,
    reviews: 1654,
    image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=500',
    category: 'Toys & Games',
    description: 'Exciting strategy board game for 2-4 players, perfect for family game night.',
    features: [
      '2-4 players',
      '60-90 minute gameplay',
      'High-quality components',
      'Ages 12+',
      'Award-winning game'
    ],
    inStock: true,
    prime: true,
  },
];
